const goalsData = [
  {
    id: 1,
    day: 1,
    mainGoal: "JavaScript",
    date: "11 July 2024",
    task: "Introduction to JavaScript",
    desc: [
      "Overview of JavaScript, its history, and its role in web development.",
      "Setting up the development environment (installing Node.js, choosing a code editor like VSCode).",
      "Writing and running your first JavaScript program ('Hello, World!').",
    ],
    status: false,
  },
  {
    id: 2,
    day: 2,
    mainGoal: "JavaScript",
    date: "12 July 2024",
    task: "JavaScript Basics",
    desc: [
      "Understanding JavaScript syntax (statements, comments, semicolons).",
      "Learning about basic operators (arithmetic, assignment, comparison, logical).",
      "Introduction to JavaScript data types (strings, numbers, booleans, null, undefined).",
    ],
    status: false,
  },
  {
    id: 3,
    day: 3,
    mainGoal: "JavaScript",
    date: "13 July 2024",
    task: "Variables and Data Types",
    desc: [
      "Declaring variables using var, let, and const.",
      "Understanding scope (global vs. local scope).",
      "Learning about reference data types (arrays, objects).",
    ],
    status: false,
  },
  {
    id: 4,
    day: 4,
    mainGoal: "JavaScript",
    date: "14 July 2024",
    task: "Control Structures: Conditionals",
    desc: [
      "Using if, else if, and else statements for conditional logic.",
      "Using switch statements for multiple branches based on value.",
      "Practicing with examples and exercises.",
    ],
    status: false,
  },
  {
    id: 5,
    day: 5,
    mainGoal: "JavaScript",
    date: "15 July 2024",
    task: "Control Structures: Loops",
    desc: [
      "Understanding the use of loops to repeat code (for, while, do-while loops).",
      "Learning about break and continue statements.",
      "Practicing with loop exercises and examples.",
    ],
    status: false,
  },
  {
    id: 6,
    day: 6,
    mainGoal: "JavaScript",
    date: "16 July 2024",
    task: "Functions",
    desc: [
      "Defining and invoking functions using function declarations.",
      "Understanding function expressions and arrow functions.",
      "Learning about parameters, arguments, and return values.",
    ],
    status: false,
  },
  {
    id: 7,
    day: 7,
    mainGoal: "JavaScript",
    date: "17 July 2024",
    task: "Objects and Arrays",
    desc: [
      "Creating and manipulating objects (properties, methods).",
      "Understanding the 'this' keyword in object methods.",
      "Creating and manipulating arrays (methods like push, pop, shift, unshift).",
    ],
    status: false,
  },
  {
    id: 8,
    day: 8,
    mainGoal: "JavaScript",
    date: "18 July 2024",
    task: "DOM Manipulation",
    desc: [
      "Selecting DOM elements using methods like getElementById, querySelector, etc.",
      "Manipulating DOM elements (changing content, attributes, styles).",
      "Handling events (click, input, etc.) and adding event listeners.",
    ],
    status: false,
  },
  {
    id: 9,
    day: 9,
    mainGoal: "JavaScript",
    date: "19 July 2024",
    task: "Asynchronous JavaScript: Callbacks",
    desc: [
      "Understanding the concept of asynchronous programming.",
      "Learning about callbacks and how to use them.",
      "Practicing with examples of asynchronous operations using callbacks.",
    ],
    status: false,
  },
  {
    id: 10,
    day: 10,
    mainGoal: "JavaScript",
    date: "20 July 2024",
    task: "Asynchronous JavaScript: Promises",
    desc: [
      "Introduction to Promises and how they work.",
      "Creating and handling Promises in JavaScript.",
      "Using Promises for asynchronous operations (fetching data, etc.).",
    ],
    status: false,
  },
  {
    id: 11,
    day: 11,
    mainGoal: "JavaScript",
    date: "21 July 2024",
    task: "Asynchronous JavaScript: Async/Await",
    desc: [
      "Understanding async and await keywords.",
      "Converting Promises to async/await syntax.",
      "Practicing with examples of asynchronous code using async/await.",
    ],
    status: false,
  },
  {
    id: 12,
    day: 12,
    mainGoal: "JavaScript",
    date: "22 July 2024",
    task: "ES6 Features",
    desc: [
      "Learning about let and const for variable declarations.",
      "Using template literals for string interpolation.",
      "Understanding destructuring for arrays and objects.",
      "Exploring spread and rest operators.",
    ],
    status: false,
  },
  {
    id: 13,
    day: 13,
    mainGoal: "JavaScript",
    date: "23 July 2024",
    task: "More ES6 Features",
    desc: [
      "Using default parameters in functions.",
      "Understanding the concept of modules in ES6.",
      "Learning about the Symbol data type.",
    ],
    status: false,
  },
  {
    id: 14,
    day: 14,
    mainGoal: "JavaScript",
    date: "24 July 2024",
    task: "Advanced Topics: Prototypes and Inheritance",
    desc: [
      "Understanding prototypes and prototype chain.",
      "Creating and using prototypes for inheritance.",
      "Exploring ES6 classes and class inheritance.",
    ],
    status: false,
  },
  {
    id: 15,
    day: 15,
    mainGoal: "JavaScript",
    date: "25 July 2024",
    task: "Advanced Topics: Closures",
    desc: [
      "Understanding the concept of closures in JavaScript.",
      "Learning about lexical scoping and closures.",
      "Practicing with examples and use cases of closures.",
    ],
    status: false,
  },
  {
    id: 16,
    day: 16,
    mainGoal: "JavaScript",
    date: "26 July 2024",
    task: "Advanced Topics: Event Loop",
    desc: [
      "Understanding how the JavaScript event loop works.",
      "Learning about the call stack, web APIs, and task queue.",
      "Exploring examples to understand event loop behavior.",
    ],
    status: false,
  },
  {
    id: 17,
    day: 17,
    mainGoal: "JavaScript",
    date: "27 July 2024",
    task: "Working with APIs: Fetch API",
    desc: [
      "Introduction to the Fetch API for making HTTP requests.",
      "Fetching data from external APIs using fetch.",
      "Handling JSON data and errors with fetch.",
    ],
    status: false,
  },
  {
    id: 18,
    day: 18,
    mainGoal: "JavaScript",
    date: "28 July 2024",
    task: "Working with APIs: AJAX",
    desc: [
      "Understanding AJAX and its role in asynchronous web applications.",
      "Making AJAX requests using XMLHttpRequest.",
      "Handling responses and updating the DOM with AJAX.",
    ],
    status: false,
  },
  {
    id: 19,
    day: 19,
    mainGoal: "JavaScript",
    date: "29 July 2024",
    task: "Debugging and Testing",
    desc: [
      "Using console methods for debugging (console.log, console.error, etc.).",
      "Setting and using breakpoints in browser developer tools.",
      "Introduction to testing JavaScript code with frameworks like Jest.",
    ],
    status: false,
  },
  {
    id: 20,
    day: 20,
    mainGoal: "JavaScript",
    date: "30 July 2024",
    task: "Performance Optimization",
    desc: [
      "Minifying JavaScript files to reduce file size.",
      "Implementing caching strategies to improve performance.",
      "Using techniques like debouncing and throttling for event handling optimization.",
    ],
    status: false,
  },
  {
    id: 21,
    day: 21,
    mainGoal: "JavaScript",
    date: "31 July 2024",
    task: "Project Day 1",
    desc: [
      "Starting a simple project to apply learned concepts.",
      "Planning and setting up the project structure.",
      "Implementing basic functionalities and features.",
    ],
    status: false,
  },
  {
    id: 22,
    day: 22,
    mainGoal: "JavaScript",
    date: "1 August 2024",
    task: "Project Day 2",
    desc: [
      "Continuing to build and enhance the project.",
      "Adding more features and functionalities.",
      "Debugging and testing the project code.",
    ],
    status: false,
  },
  {
    id: 23,
    day: 23,
    mainGoal: "JavaScript",
    date: "2 August 2024",
    task: "Project Day 3",
    desc: [
      "Refactoring code for better readability and performance.",
      "Implementing user authentication and authorization.",
      "Adding responsive design and improving UI/UX.",
    ],
    status: false,
  },
  {
    id: 24,
    day: 24,
    mainGoal: "JavaScript",
    date: "3 August 2024",
    task: "Project Day 4",
    desc: [
      "Integrating third-party APIs for additional functionality.",
      "Implementing data persistence using local storage or a backend server.",
      "Writing comprehensive documentation for the project.",
    ],
    status: false,
  },
  {
    id: 25,
    day: 25,
    mainGoal: "JavaScript",
    date: "4 August 2024",
    task: "Project Day 5",
    desc: [
      "Performing security audits and implementing best practices.",
      "Optimizing performance and resolving any remaining bugs.",
      "Preparing for project deployment.",
    ],
    status: false,
  },
  {
    id: 26,
    day: 26,
    mainGoal: "JavaScript",
    date: "5 August 2024",
    task: "Deployment",
    desc: [
      "Choosing a deployment platform (Heroku, Netlify, AWS, etc.).",
      "Configuring deployment settings and environment variables.",
      "Deploying the project and testing in a live environment.",
    ],
    status: false,
  },
  {
    id: 27,
    day: 27,
    mainGoal: "JavaScript",
    date: "6 August 2024",
    task: "Continuous Learning and Improvement",
    desc: [
      "Reflecting on the learning journey and identifying areas for improvement.",
      "Exploring advanced JavaScript topics not covered in the initial 30-day plan.",
      "Joining developer communities and participating in open-source projects.",
    ],
    status: false,
  },
  {
    id: 28,
    day: 28,
    mainGoal: "JavaScript",
    date: "7 August 2024",
    task: "Review and Recap",
    desc: [
      "Reviewing key concepts and revisiting challenging topics.",
      "Creating a personal portfolio showcasing the JavaScript project.",
      "Preparing for technical interviews and coding challenges.",
    ],
    status: false,
  },
  {
    id: 29,
    day: 29,
    mainGoal: "JavaScript",
    date: "8 August 2024",
    task: "Career Preparation",
    desc: [
      "Building a strong resume highlighting JavaScript skills and projects.",
      "Practicing coding interview questions on platforms like LeetCode and HackerRank.",
      "Networking with professionals in the tech industry.",
    ],
    status: false,
  },
  {
    id: 30,
    day: 30,
    mainGoal: "JavaScript",
    date: "9 August 2024",
    task: "Final Project Presentation",
    desc: [
      "Presenting the completed JavaScript project to peers or mentors.",
      "Receiving feedback and suggestions for improvement.",
      "Celebrating the achievement and setting new learning goals.",
    ],
    status: false,
  },
  {
    id: 3,
    mainGoal: "C++",
    day: 1,
    date: "2024-07-01",
    desc: ["Understand OOP", "Practice data structures"],
    status: false,
  },
  {
    id: 4,
    mainGoal: "C++",
    day: 2,
    date: "2024-07-02",
    desc: ["Explore STL", "Implement algorithms"],
    status: true,
  },
];

export { goalsData };
