const posts = [
  {
    profileImg: "https://randomuser.me/api/portraits/men/86.jpg",
    fullName: "Random User",
    content:
      "Early Life and Training: Arijit Singh was born in West Bengal and began his music training at a young age, influenced by his musically inclined family. Career Beginnings: He participated in the reality show Fame Gurukul in 2005 and later moved to Mumbai to pursue a career in music1. Breakthrough: Singh gained recognition with the song “Tum Hi Ho” from Aashiqui 2 in 2013, which won him several awards2.Early Life and Training: Arijit Singh was born in West Bengal and began his music training at a young age, influenced by his musically inclined family. Career Beginnings: He participated in the reality show Fame Gurukul in 2005 and later moved to Mumbai to pursue a career in music1. Breakthrough: Singh gained recognition with the song “Tum Hi Ho” from Aashiqui 2 in 2013, which won him several awards2.Early Life and Training: Arijit Singh was born in West Bengal and began his music training at a young age, influenced by his musically inclined family. Career Beginnings: He participated in the reality show Fame Gurukul in 2005 and later moved to Mumbai to pursue a career in music1. Breakthrough: Singh gained recognition with the song “Tum Hi Ho” from Aashiqui 2 in 2013, which won him several awards2.",
    likes: "10",
    comments: "5",
    shares: "2",
    time: "1h",
    privacy: "public",
    isFollowing: true,
  },
  {
    profileImg: "https://randomuser.me/api/portraits/men/34.jpg",
    fullName: "John Doe",
    content: "This is an example post.",
    likes: 120,
    comments: 30,
    shares: 15,
    time: "2 hours ago",
    isFollowing: false,
    privacy: "followers",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/men/78.jpg",
    fullName: "Jane Smith",
    content: "postimage.jpg",
    likes: 200,
    comments: 50,
    shares: 25,
    time: "3 hours ago",
    isFollowing: true,
    privacy: "onlyme",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/women/12.jpg",
    fullName: "Emily Johnson",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod, nunc id aliquet tincidunt, nunc nunc tincidunt elit, id aliquet nunc nunc id.",
    likes: 50,
    comments: 10,
    shares: 5,
    time: "4 hours ago",
    isFollowing: true,
    privacy: "public",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/men/45.jpg",
    fullName: "Michael Brown",
    content:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.",
    likes: 80,
    comments: 20,
    shares: 8,
    time: "5 hours ago",
    isFollowing: false,
    privacy: "onlyme",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/women/67.jpg",
    fullName: "Sophia Wilson",
    content:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    likes: 30,
    comments: 5,
    shares: 2,
    time: "6 hours ago",
    isFollowing: true,
    privacy: "followers",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/men/23.jpg",
    fullName: "Daniel Davis",
    content:
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    likes: 70,
    comments: 15,
    shares: 7,
    time: "7 hours ago",
    isFollowing: false,
    privacy: "public",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/women/89.jpg",
    fullName: "Olivia Martinez",
    content:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    likes: 90,
    comments: 25,
    shares: 12,
    time: "8 hours ago",
    isFollowing: true,
    privacy: "onlyme",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/men/56.jpg",
    fullName: "William Anderson",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    likes: 40,
    comments: 8,
    shares: 4,
    time: "9 hours ago",
    isFollowing: false,
    privacy: "followers",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/women/34.jpg",
    fullName: "Emma Thompson",
    content:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    likes: 60,
    comments: 12,
    shares: 6,
    time: "10 hours ago",
    isFollowing: true,
    privacy: "public",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/men/78.jpg",
    fullName: "James Wilson",
    content:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    likes: 100,
    comments: 30,
    shares: 15,
    time: "11 hours ago",
    isFollowing: false,
    privacy: "onlyme",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/women/45.jpg",
    fullName: "Ava Davis",
    content:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.",
    likes: 120,
    comments: 40,
    shares: 20,
    time: "12 hours ago",
    isFollowing: true,
    privacy: "followers",
  },
  {
    profileImg: "https://randomuser.me/api/portraits/men/67.jpg",
    fullName: "Benjamin Johnson",
    content:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    likes: 80,
    comments: 20,
    shares: 10,
    time: "13 hours ago",
    isFollowing: false,
    privacy: "public",
  },
];

export default posts;
